# Site settings
name: Scaffold
version: 0.2.5
author: Max Quattromani
email: max@maxquattromani.com
description: ""
baseurl: "/scaffold/"
url: "http://maxquattromani.com"
author: "Max Quattromani"
twitter_username: maxquattromani
github_username:  quattromani

# Build settings
markdown: kramdown
permalink: pretty
highlighter: true

exclude: ['node_modules', 'scss', 'DAM']

google_analytics: true
google_analytics_id: UA-50387096-4
jquery_version: 1.9.0

footer: "This is my footer"
